### ISSUE TITLE
VR Release/Build

### ISSUE THREAD

**Issue by nephatrine** [Seally/yastm#3]
The releases for this only have prebuilt SE/AE builds it seems. Is there a prebuilt VR binary? I don't have a dev environment set up right now to build it myself but would love to try it out.

**Comment by Seally** [comment]
This was the last version I compiled and packaged I think: https://1drv.ms/u/s!Ai-mPHDN6-1RhN4vulG1rofjIWeiYQ?e=rONovQ
Note that one specific difference from the SE version is that, because of the lack of ESL support in VR, I made the decision to use Editor IDs to refer to specific soul gem forms instead of the standard `[<formID>, <espName>]`, so that it will be more resilient to plugin merging. 

However, this method has a caveat that, by default, the game never loads the Editor IDs of certain form types (SLGM forms included), so you need another plugin that will do this: [PowerOfThree's Tweaks VR](https://www.nexusmods.com/skyrimspecialedition/mods/59510)

I do intend to release the mod properly some day, but right now I'm mostly on break from Skyrim.

**Comment by nephatrine** [comment]
No problem! I'm already using got po3's tweaks so that's great. It's easy to get burned out on Skyrim so take your time and thank you for the work you've already done!
